package load

val urls = arrayOf(
        "icons/exit-button-colored.png",
        "icons/exit-button.png",
        "icons/start-button-colored.png",
        "icons/start-button.png",
        "icons/settings-button-colored.png",
        "icons/settings-button.png",
        "icons/cancel-dark.png",
        "icons/cancel-light.png",
        "tiles/dark-floor-1.png",
        "tiles/floor-grass-1.png",
        "tiles/floor-grass-2.png",
        "tiles/floor-grass-3.png",
        "tiles/floor-grass-4.png",
        "tiles/stone-ice-1.png",
        "tiles/stone-ice-2.png",
        "tiles/stone-ice-3.png",
        "tiles/stone-1.png",
        "tiles/stone-2.png",
        "tiles/stone-3.png",
        "items/doorclosed.png",
        "items/dooropen.png",
        "items/bombamount.png",
        "items/key.png",
        "items/powerup_heart.png",
        "items/powerup_sword.png",
        "items/speedup.png",
        "items/bombpower.png",
        "items/heartfull.png",
        "tiles/brick-2.png",
        "items/sword.png",
        "items/bomb.png",
        "items/flame.png",
        "items/frostbomb.png",
        "items/explosion_red.png",
        "items/explosion_frost.png",
        "levels/entry_star.png",
        "levels/entry_star_passed.png",
        "levels/checkpoint_0.png",
        "levels/checkpoint_0_passed.png",
        "levels/checkpoint_1.png",
        "levels/checkpoint_1_passed.png"
)

